[package]
name = "upgrader_api"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-canister-macros = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
