name: 'Setup Python'
description: 'Adds python and pip as the package installer'

runs:
  using: 'composite'
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: 'Install PIP'
      shell: bash
      run: python -m pip install --upgrade pip
