name: 'Code benchmarks'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
  merge_group:
    types: [checks_requested]
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .
  # sscache environment variables
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'

jobs:
  bench-station:
    name: 'bench-station:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: 'Run Station Benchmarks'
        run: ./scripts/benchmark-canister.sh ./core/station/impl
