name: 'Deterministic builds'

on:
  workflow_dispatch: null

jobs:
  build-station:
    name: 'build-station:optional'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: 'Deterministic build'
        run: |
          ./scripts/docker-build.sh --station
      - name: 'Built hash'
        run: |
          BUILD_HASH=$(cat ./artifacts/station/station.wasm.gz.sha256)
          echo "built hash: $BUILD_HASH"
  build-upgrader:
    name: 'build-upgrader:optional'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: 'Deterministic build'
        run: |
          ./scripts/docker-build.sh --upgrader
      - name: 'Built hash'
        run: |
          BUILD_HASH=$(cat ./artifacts/upgrader/upgrader.wasm.gz.sha256)
          echo "built hash: $BUILD_HASH"
  build-control-panel:
    name: 'build-control-panel:optional'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: 'Deterministic build'
        run: |
          ./scripts/docker-build.sh --control-panel
      - name: 'Built hash'
        run: |
          BUILD_HASH=$(cat ./artifacts/control-panel/control_panel.wasm.gz.sha256)
          echo "built hash: $BUILD_HASH"
  build-wallet-dapp:
    name: 'build-wallet-dapp:optional'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: 'Deterministic build'
        run: |
          ./scripts/docker-build.sh --wallet-dapp
      - name: 'Built hash'
        run: |
          BUILD_HASH=$(cat ./artifacts/wallet-dapp/wallet_dapp.wasm.gz.sha256)
          echo "built hash: $BUILD_HASH"
